name: Verification

on:
  schedule:
    - cron: "0 7 1,16 * *"
  workflow_dispatch:

jobs:
  verification:
    permissions:
      id-token: write
      contents: write
    name: Run verification
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/checkout@v3

      - name: Load Symfem cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/.cache/symfem
          key: symfem-cache

      - name: Clone Symfem
        uses: actions/checkout@v3
        with:
          path: ./symfem
          repository: mscroggs/symfem
          ref: main
      - name: Install Symfem
        run: |
            cd symfem
            python3 -m pip install .[optional]

      - run: python3 -m pip install -r requirements.txt
        name: Install requirements

      - name: Install implementations
        run: |
          python3 -m pip install setuptools
          python3 install_implementations.py --install-type verification

      - run: mkdir ../verification
        name: Make dir
      - run: python3 verify.py ../verification/verification.json --processes 4
        name: Run verification
      - run: |
          cd ../verification
          git init
          git checkout -b verification
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "verification.json"
          git remote add origin https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/DefElement/defelement.com.git
          git push -u origin verification --force
        name: Push to GitHub
